import SyntaxHighlighter from 'react-syntax-highlighter'
import { atelierCaveDark } from 'react-syntax-highlighter/dist/esm/styles/hljs'
import { VsCode } from '../../Components/VsCode'

export function SponsorBlock() {
  const code = `    {
    "autoSkipOnMusicVideosUpdate":true,
    "categoryPillUpdate":true,
    "categorySelections":[
       {
          "name":"sponsor",
          "option":2
       },
       {
          "name":"poi_highlight",
          "option":1
       },
       {
          "name":"exclusive_access",
          "option":0
       },
       {
          "name":"chapter",
          "option":0
       },
       {
          "name":"selfpromo",
          "option":2
       },
       {
          "name":"interaction",
          "option":2
       },
       {
          "name":"intro",
          "option":2
       },
       {
          "name":"outro",
          "option":2
       },
       {
          "name":"preview",
          "option":2
       },
       {
          "name":"filler",
          "option":1
       },
       {
          "name":"music_offtopic",
          "option":1
       }
    ],
    "chapterCategoryAdded":true,
    "invidiousInstances":[
       "www.youtubekids.com",
       "inv.bp.projectsegfau.lt",
       "inv.citw.lgbt",
       "inv.in.projectsegfau.lt",
       "inv.makerlab.tech",
       "inv.pistasjis.net",
       "inv.tux.pizza",
       "inv.zzls.xyz",
       "invidious.0011.lt",
       "invidious.io.lol",
       "invidious.lunar.icu",
       "invidious.no-logs.com",
       "invidious.projectsegfau.lt",
       "invidious.protokolla.fi",
       "invidious.slipfox.xyz",
       "invidious.tiekoetter.com",
       "iv.ggtyler.dev",
       "iv.melmac.space",
       "iv.nboeck.de",
       "onion.tube",
       "vid.priv.au",
       "vid.puffyan.us",
       "yewtu.be",
       "yt.artemislena.eu",
       "yt.oelrichsgarcia.de",
       "invidious.privacydev.net",
       "invidious.snopyta.org"
    ],
    "isVip":false,
    "minutesSaved":241.7387754666667,
    "permissions":{
       "chapter":false,
       "exclusive_access":true,
       "filler":true,
       "interaction":true,
       "intro":true,
       "music_offtopic":true,
       "outro":true,
       "poi_highlight":true,
       "preview":true,
       "selfpromo":true,
       "sponsor":true
    },
    "showDeArrowPromotion":false,
    "showPopupDonationCount":1,
    "showZoomToFillError2":false,
    "skipCount":373,
    "userID":"vol9IvLOIYxBytuxeQn2qfsYOfzdcjczzfQE",
    "unsubmittedSegments":{
       
    },
    "defaultCategory":"chooseACategory",
    "renderSegmentsAsChapters":false,
    "whitelistedChannels":[
       
    ],
    "forceChannelCheck":false,
    "sponsorTimesContributed":0,
    "submissionCountSinceCategories":0,
    "showTimeWithSkips":true,
    "disableSkipping":false,
    "muteSegments":true,
    "fullVideoSegments":true,
    "fullVideoLabelsOnThumbnails":true,
    "manualSkipOnFullVideo":true,
    "trackViewCount":true,
    "trackViewCountInPrivate":true,
    "trackDownvotes":true,
    "dontShowNotice":false,
    "noticeVisibilityMode":3,
    "hideVideoPlayerControls":false,
    "hideInfoButtonPlayerControls":false,
    "hideDeleteButtonPlayerControls":false,
    "hideUploadButtonPlayerControls":false,
    "hideSkipButtonPlayerControls":false,
    "hideDiscordLaunches":0,
    "hideDiscordLink":false,
    "supportInvidious":false,
    "serverAddress":"https://sponsor.ajay.app",
    "minDuration":0,
    "skipNoticeDuration":4,
    "audioNotificationOnSkip":false,
    "checkForUnlistedVideos":false,
    "testingServer":false,
    "refetchWhenNotFound":true,
    "ytInfoPermissionGranted":false,
    "allowExpirements":true,
    "showDonationLink":true,
    "showUpsells":true,
    "showNewFeaturePopups":true,
    "donateClicked":0,
    "autoHideInfoButton":true,
    "autoSkipOnMusicVideos":false,
    "scrollToEditTimeUpdate":false,
    "showChapterInfoMessage":true,
    "darkMode":true,
    "showCategoryGuidelines":true,
    "showCategoryWithoutPermission":false,
    "showSegmentNameInChapterBar":true,
    "useVirtualTime":true,
    "showSegmentFailedToFetchWarning":true,
    "allowScrollingToEdit":true,
    "deArrowInstalled":false,
    "categoryPillColors":{
       
    },
    "skipKeybind":{
       "key":"Enter"
    },
    "startSponsorKeybind":{
       "key":";"
    },
    "submitKeybind":{
       "key":"'"
    },
    "nextChapterKeybind":{
       "key":"ArrowRight",
       "ctrl":true
    },
    "previousChapterKeybind":{
       "key":"ArrowLeft",
       "ctrl":true
    },
    "payments":{
       "licenseKey":null,
       "lastCheck":0,
       "lastFreeCheck":0,
       "freeAccess":false,
       "chaptersAllowed":false
    },
    "colorPalette":{
       "red":"#780303",
       "white":"#ffffff",
       "locked":"#ffc83d"
    },
    "barTypes":{
       "preview-chooseACategory":{
          "color":"#ffffff",
          "opacity":"0.7"
       },
       "sponsor":{
          "color":"#00d400",
          "opacity":"0.7"
       },
       "preview-sponsor":{
          "color":"#007800",
          "opacity":"0.7"
       },
       "selfpromo":{
          "color":"#ffff00",
          "opacity":"0.7"
       },
       "preview-selfpromo":{
          "color":"#bfbf35",
          "opacity":"0.7"
       },
       "exclusive_access":{
          "color":"#008a5c",
          "opacity":"0.7"
       },
       "interaction":{
          "color":"#cc00ff",
          "opacity":"0.7"
       },
       "preview-interaction":{
          "color":"#6c0087",
          "opacity":"0.7"
       },
       "intro":{
          "color":"#00ffff",
          "opacity":"0.7"
       },
       "preview-intro":{
          "color":"#008080",
          "opacity":"0.7"
       },
       "outro":{
          "color":"#0202ed",
          "opacity":"0.7"
       },
       "preview-outro":{
          "color":"#000070",
          "opacity":"0.7"
       },
       "preview":{
          "color":"#008fd6",
          "opacity":"0.7"
       },
       "preview-preview":{
          "color":"#005799",
          "opacity":"0.7"
       },
       "music_offtopic":{
          "color":"#ff9900",
          "opacity":"0.7"
       },
       "preview-music_offtopic":{
          "color":"#a6634a",
          "opacity":"0.7"
       },
       "poi_highlight":{
          "color":"#ff1684",
          "opacity":"0.7"
       },
       "preview-poi_highlight":{
          "color":"#9b044c",
          "opacity":"0.7"
       },
       "filler":{
          "color":"#7300FF",
          "opacity":"0.9"
       },
       "preview-filler":{
          "color":"#2E0066",
          "opacity":"0.7"
       }
    }
 }`

  return (
    <VsCode.Content>
      <SyntaxHighlighter
        language="markdown"
        style={atelierCaveDark}
        showLineNumbers
      >
        {code}
      </SyntaxHighlighter>
    </VsCode.Content>
  )
}
